networks:
  penpot:
    external: true
    name: localdev

services:
  frontend:
    image: "penpotapp/frontend:latest"
    container_name: penpot-frontend
    restart: always
    networks: [ penpot ]
    ports:
      - "9001:80"
    env_file: [ .env ]
    environment:
      VIRTUAL_HOST: penpot.docker
      PENPOT_PUBLIC_URI: http://penpot.docker
    depends_on:
      - backend
      - exporter
    volumes:
      - ./docker/assets:/opt/data/assets
      - ./docker/nginx.conf:/etc/nginx/nginx.conf.template

  backend:
    image: "penpotapp/backend:latest"
    container_name: penpot-backend
    networks: [ penpot ]
    restart: always
    env_file: [ .env ]
    environment:
      PENPOT_PUBLIC_URI: http://penpot.docker:9001
    depends_on:
      - postgres
      - redis
    volumes:
      - ./docker/assets:/opt/data/assets

  exporter:
    image: "penpotapp/exporter:latest"
    container_name: penpot-exporter
    networks: [ penpot ]
    restart: always
    env_file: [ .env ]

  postgres:
    image: "postgres:15"
    container_name: penpot-postgres
    networks: [ penpot ]
    restart: always
    env_file: [ .env ]
    stop_signal: SIGINT
    volumes:
      - ./docker/data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: penpot-redis
    networks: [ penpot ]
    restart: always
    env_file: [ .env ]

  # used as temporary SMTP server.
  mailcatch:
    image: sj26/mailcatcher:latest
    container_name: penpot-mailcatch
    networks: [ penpot ]
    restart: always
    ports:
      - "1080:1080"
    expose:
      - "1025"
    env_file: [ .env ]