networks:
  penpot:
    external: true
    name: localdev

services:
  frontend:
    image: "penpotapp/frontend:latest"
    container_name: penpot_frontend
    restart: always
    networks: [ penpot ]
    ports:
      - "9001:80"
    env_file:
      - ./docker/.env
    environment:
      VIRTUAL_HOST: penpot.docker
      NODE_ENV: dev
      PENPOT_FLAGS: disable-secure-session-cookies enable-demo-users enable-registration enable-login-with-password
    depends_on:
      - backend
      - exporter
    volumes:
      - ./docker/assets:/opt/data/assets

  backend:
    image: "penpotapp/backend:latest"
    container_name: penpot_backend
    restart: always
    networks: [ penpot ]
    env_file:
      - ./docker/.env
    environment:
      PENPOT_FLAGS: disable-secure-session-cookies enable-registration enable-demo-users enable-login-with-password disable-email-verification enable-smtp enable-prepl-server
      PENPOT_PREPL_HOST: 0.0.0.0
      # this was previously http://localhost:9001
      PENPOT_PUBLIC_URI: http://penpot.docker:9001
      PENPOT_REDIS_URI: redis://penpot-redis/0
      PENPOT_ASSETS_STORAGE_BACKEND: assets-fs
      PENPOT_STORAGE_ASSETS_FS_DIRECTORY: /opt/data/assets
      PENPOT_TELEMETRY_ENABLED: false
    depends_on:
      - postgres
      - redis
    volumes:
      - ./docker/assets:/opt/data/assets

  exporter:
    image: "penpotapp/exporter:latest"
    container_name: penpot-exporter
    restart: always
    networks: [ penpot ]
    env_file:
      - ./docker/.env

  postgres:
    image: "postgres:15"
    container_name: penpot_postgres
    restart: always
    networks: [ penpot ]
    stop_signal: SIGINT
    env_file:
      - ./docker/.env
    volumes:
      - ./docker/data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: penpot_redis
    restart: always
    networks: [ penpot ]
    env_file:
      - ./docker/.env

  # used as temporary SMTP server.
  mailcatch:
    image: sj26/mailcatcher:latest
    container_name: penpot_mailcatch
    restart: always
    networks: [ penpot ]
    expose:
      - '1025'
    ports:
      - "1080:1080"
